#
# #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#   This file is part of the Smart Developer Hub Project:
#     http://www.smartdeveloperhub.org/
#
#   Center for Open Middleware
#     http://www.centeropenmiddleware.com/
# #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#   Copyright (C) 2015 Center for Open Middleware.
# #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#   Artifact    : org.smartdeveloperhub.curator:sdh-curator-connector:0.2.0-SNAPSHOT
#   Bundle      : sdh-curator-connector-0.2.0-SNAPSHOT.jar
# #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#

PREFIX amqp: <http://www.smartdeveloperhub.org/vocabulary/amqp#>
PREFIX types: <http://www.smartdeveloperhub.org/vocabulary/types#>

SELECT ?broker ?host ?port ?virtualHost
WHERE {
  ?broker a amqp:Broker .
  OPTIONAL { ?broker amqp:host ?host . }
  OPTIONAL { ?broker amqp:port ?port . }
  OPTIONAL { ?broker amqp:virtualHost ?virtualHost . }
  FILTER (
    IF(bound(?host), datatype(?host) = types:Hostname , true) &&
    IF(bound(?port), datatype(?port) = types:Port , true) &&
    IF(bound(?virtualHost), datatype(?virtualHost) = amqp:Path, true)
  )
}
